stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: "production"

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g pnpm

build_client:
  stage: build
  image: node:18-alpine
  script:
    - cd client
    - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - client/build

build_server:
  stage: build
  image: node:18-alpine
  script:
    - cd server
    - pnpm install --frozen-lockfile
  artifacts:
    paths:
      - server/node_modules

test_client:
  stage: test
  image: node:18-alpine
  script:
    - cd client
    - pnpm install --frozen-lockfile
    - pnpm run test -- -watchAll=false

test_server:
  stage: test
  image: node:18-alpine
  script:
    - cd server
    - pnpm install --frozen-lockfile
    - pnpm run test

deploy:
  stage: deploy
  image: node:18-alpine
  script:
    - echo "Deploying to production server..."
  only:
    - master